name: 'comment-pr-link-on-asana'
description: 'Asana のコメントに GitHub Pull Requestのリンクをコメントする'
inputs:
  repo-token:
    description: 'GitHub Token'
    required: true
  asana-token:
    description: 'Asana personal access token'
    required: true¥
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
